/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 my_model.glb --transform 
Files: my_model.glb [793.41KB] > /Users/ARUR/Workspace/react-three-practice/my_model-transformed.glb [11.62KB] (99%)
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/my_model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_Mesh_head_geo001_lambert2SG001.geometry} material={materials['lambert2SG.001']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/my_model-transformed.glb')
